title: a1erf • radical root
description: full-tree public mirror of the repo. every file served. no exclusions.
theme: minima
markdown: kramdown
permalink: pretty
# keep it pure transparency. no exclude list.
